# Use the official Node.js image
FROM node:18

# Set the working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install --legacy-peer-deps

# Copy the rest of the client files
COPY . .

# Expose port 5173
EXPOSE 5173

# Start the client
CMD ["npm", "run", "dev"]
