/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [8.82KB] > C:\Users\USER\Desktop\DreamTrip-AI\client\public\models3\earth\scene-transformed.glb [274.93KB] (-3017%)
Author: Shubhanshu Soni (https://sketchfab.com/sonishubhanshu99)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/earth-37249acae18b406d8c1c160d7c0bc8e6
Title: Earth
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'

export function Earth(props) {
  const group = useRef()
  const earthRef = useRef()
  const cloudsRef = useRef()
  const { nodes, materials } = useGLTF('/models3/earth/scene-transformed.glb')
  
  // Earth material with appropriate glow
  const earthMaterial = materials.Earth.clone()
  earthMaterial.emissive = new THREE.Color(0x083764)
  earthMaterial.emissiveIntensity = 0.2
  earthMaterial.roughness = 0.7
  earthMaterial.metalness = 0.3
  
  // Create a much more visible cloud material
  const cloudMaterial = new THREE.MeshStandardMaterial({
    color: new THREE.Color(0xffffff),
    emissive: new THREE.Color(0xffffff),
    emissiveIntensity: 0.2,
    transparent: true,
    opacity: 0.95,
    depthWrite: false,
    side: THREE.DoubleSide,
    roughness: 0.5,
    metalness: 0.1
  })
  
  // Ensure proper layer stacking
  useEffect(() => {
    if (cloudsRef.current && earthRef.current) {
      // Clouds need to be clearly larger than the Earth
      cloudsRef.current.scale.set(1.06, 1.06, 1.06)
    }
  }, [])
  
  // Synchronized rotation animation with different speeds
  useFrame((state, delta) => {
    if (group.current) {
      group.current.rotation.y += delta * 0.03
    }
    
    // Faster rotation for clouds to make them more noticeable
    if (cloudsRef.current) {
      cloudsRef.current.rotation.y += delta * 0.02
    }
  })
  
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="RootNode">
          {/* Earth sphere */}
          <mesh 
            ref={earthRef}
            name="Earth_Earth_0" 
            geometry={nodes.Earth_Earth_0.geometry} 
            material={earthMaterial} 
            rotation={[-Math.PI / 2, 0, -1.544]} 
            scale={99.307} 
          />
          
          {/* Separate, very visible cloud layer */}
          <group name="Clouds" rotation={[-Math.PI / 2, 0, 0]} scale={103}>
            <mesh 
              ref={cloudsRef}
              name="Clouds_Clouds_0" 
              geometry={nodes.Clouds_Clouds_0.geometry} 
              material={cloudMaterial}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models3/earth/scene-transformed.glb')
