name: MongoDB Service Workflow

on:
  workflow_call:
    outputs:
      mongodb_uri:
        description: "MongoDB connection URI"
        value: ${{ jobs.setup-mongodb.outputs.mongodb_uri }}

jobs:
  setup-mongodb:
    name: Setup MongoDB
    runs-on: ubuntu-latest
    outputs:
      mongodb_uri: ${{ steps.output-uri.outputs.mongodb_uri }}

    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: password
        options: >-
          --health-cmd mongosh --eval "db.adminCommand('ping')"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Output MongoDB URI
        id: output-uri
        run: echo "mongodb_uri=mongodb://root:password@localhost:27017" >> $GITHUB_OUTPUT
